### ISSUE TITLE
Lyman-alpha continuum different than data

### ISSUE THREAD

**Issue by londumas** [imcgreer/simqso#25]
With desi we observe a large difference between the Lyman-alpha forest continuum in SIMQSO and in BOSS+eBOSS data. The following plot gives the stack for both cases. Would it be possible for you @imcgreer to update the lines parameters to reproduce BOSS+eBOSS stack and its variation?

Edit: The differences can be observed in many places of the spectrum but are more important
there.
Edit2: The flux is normalized in this plot.

![image](https://user-images.githubusercontent.com/3166436/43965458-8482fcc6-9c7c-11e8-9f03-26f86c6eab06.png)

**Comment by imcgreer** [comment]
A few points about the emission line model in simqso:
- the line parameters were initialized based on gaussian fits to mean spectra of BOSS quasars from early observations
- the derived parameters for some of the more prominent lines were modified in order to have the colors from simqso match those of BOSS quasars as a function of redshift (the color-z relation). since these constraints were obtained from broadband photometry they are only really sensitive to the strongest (highest EW) lines.
- however, and I continually stress this point, **the simqso model is an attempt to reconstruct the _intrinsic_ properties of quasar spectra, not the properties observed by any single survey.** if you directly compare simqso spectra to BOSS spectra, you are not comparing apples-to-apples. you **must** apply the BOSS selection function to the simqso sample, and only compare the simulated quasars that **would have been selected** by BOSS to the observed sample. this actually has a serious effect on the observed spectra, as the selection function induces biases in the observed sample, particularly for the Lya forest quasars at z~2.5 (see, e.g., Worseck & Prochaska 2011).

With those points in mind, it is quite straightforward to tweak the emission line model in simqso if you feel it is not performing well (and indeed I have no doubt it needs improvement). See the example here: https://github.com/imcgreer/simqso/blob/master/examples/bossqsos.py#L83

The full list of emission lines and their associated parameters for various versions of the model are described here:
https://github.com/imcgreer/simqso/blob/master/examples/EmissionLineTemplates.ipynb
It's also simple to add new emission lines through the API, see, e.g, https://github.com/imcgreer/simqso/blob/master/examples/z5LyaDust.ipynb where spectra are created that contain only power-law continuum and a single Lya emission line.

For example, one might infer that simqso has overpredicted the emission from the FeIII:UV1 complex at 1122A based on the plot above, in which case you might add something like this to the model parameters:
`'scaleEWs':{'FeIII:UV1':0.5,...}`
This would reduce the mean EW of that emission feature by half. See also https://github.com/imcgreer/simqso/blob/master/simqso/sqmodels.py#L176 for an example of another "tweaked" emission line model implemented in the code.

There is code already present in simqso for calculating the XDQSO probabilities used by BOSS and eBOSS for target selection (see the code starting here https://github.com/imcgreer/simqso/blob/master/sdss/ebosscore.py#L134). It should be straightforward to take the derived SDSS photometry from your model quasars, apply the BOSS/eBOSS selection function, and then compare the photometry of that sample to the observations. Following this procedure should lead to a less biased model.

**Comment by londumas** [comment]
Thank you @imcgreer, I have transmitted your answer to our working group, hopefully someone will take/have the time to work on this.

**Comment by londumas** [comment]
fixed.
